# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93eca11dc87b2828217eaf7859043bdf50ff5d17da2672dadbde5aaea126254c9a7befbc3e5894b81b0450399019f89e8749cbd1baf2407e66e8063fc8cab522

test:
  secret_key_base: 1bc610213c109adf4c7430fceed321c8c24c7bd0a01ac2ec8e3eb96e3f9d3c58858960f28c5857b31ccb095708603c12525b527906e3c9a41448e5140167c239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
